

export const getUser = async () => {
    try {

    } catch (error) {

    }
}